### ISSUE TITLE
Could not retrieve Graph Token

### ISSUE THREAD

**Issue by jignesh-stp** [microsoftgraph/msgraph-training-teamsapp-dotnet#3]
I am not able to retrieve a graph token by following the provided demo at https://docs.microsoft.com/en-us/graph/tutorials/teams I followed this demo till this point https://docs.microsoft.com/en-us/graph/tutorials/teams?tutorial-step=4 from where I could side load the app into MS Teams. The issue I faced was, the consent dialogue is not showing up, instead the app show's login in pop up. Once I logged in, the pop would keep showing up and diapering unlit it ask me to login again. In the backend I keep getting the 403 consent required error messages.

**Comment by jasonjoh** [comment]
Sorry you're having trouble! After you login, were you asked to consent to anything?

Check your app registration's "Expose an API" page and verify it matches the steps from "Configure Teams single sign-on" in https://docs.microsoft.com/en-us/graph/tutorials/teams?tutorial-step=2.

**Comment by jignesh-stp** [comment]
Hi Jason, thank you for getting back. This issues has been resolved. I am not 100% sure how but I guess it was something to do with permission consent.
